# Plugins
gems:
   - jekyll-paginate

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            'Marcus Efraimsson'
tagline:          "Let's Get Personal"
description:      "Marcus Efraimsson is a software developer, thinker, blogger with an appetite for technical challenges and new technology."
url:              https://marcus-e.se
baseurl:          '/'
paginate:         5
paginate_path:    "/page/:num"

meta:
    keywords:     'Marcus, Efraimsson, Developer, Computer, Programming, .NET, C#, ASP.NET, Code, Blog, Stockholm, Software Development'
    description:  "Marcus Efraimsson is a software developer and blogger from Stockholm, Sweden."
author:
  name:           'Marcus Efraimsson'
  first_name:     Marcus
  lastname:       Efraimsson
  google:         https://plus.google.com/111244687668180692577
  twitter:        https://twitter.com/mefraimsson
  facebook:       https://www.facebook.com/marcus.efraimsson
  linkedin:       https://www.linkedin.com/in/marcusefraimsson
  github:         https://github.com/marefr
  stack_overflow: http://stackoverflow.com/users/988019/marefr

# Custom vars
disqus_shortname: marcus-e
analytics:        UA-37826303-2
facebook_appid:   828922030493446

github:
  repo:           https://github.com/marefr/marefr.github.io

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
      disqus: true
      disqus_comment_count: true
      sitemap:
        changefreq:         weekly
        priority:           0.9
